### ISSUE TITLE
graph.js

### ISSUE THREAD

**Issue by hadley** [COSTDataExpo2013/HareKaplan#8]
- It's not actually js, but is html?
- It feels a bit weird to have google analytics code in here

My ability to rapidly review js/D3 code is much less than my ability to rapidly review R code, but here goes
- A consistent code style would make it easier to read
- Turn data into individual variables seems inelegant. Why not use `root["2008"]`, `root["all"]` etc? (plus root isn't a very descriptive name). That would avoid the icky `eval("root_" + year_select)`.
- In fact, maybe the UI choice should be between "all", 2008, 2009 and 2010. i.e. don't make it a two level selection. That would simplify the ui and the server code
- Is it really necessary to have a colour blind mode? Why not always use blue?

**Comment by andeek** [comment]
Addressed the html/google analytics code issues and cleaned up some weird spacing issued in the code in 4667744fd3c02ca45a4210a3940f92a0c45c61f6. Also removed color blind mode, always using blue.

**Comment by andeek** [comment]
changed data structure to not longer need "icky" `eval` in 0c1a3e0248735e41ddf936732f8db8515a5192b2
