### ISSUE TITLE
Data cleaning

### ISSUE THREAD

**Issue by hadley** [COSTDataExpo2013/HareKaplan#9]
Currently happens in two places (inside and outside of server function), and is rather slow. Why not do the computation once and cache the results? (along with a function to recompute)

**Comment by erichare** [comment]
Fixed in 2fe108a62fe784fb610621fe68656fb86b147448. The data cleaning now occurs in code/data_munging.R, which produces an RData object used by the app and the paper code. This will be documented in the README
